kind: pipeline
name: build-my-site
type: docker

steps:
- name: build
  image: leins275/alg-dstruct
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind --leak-check=full ./a.out

- name: feedback
  image: jmccann/drone-github-comment:1
  environment:
    api_token: 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
  when: 
    event: pull_request
  message: "Done!"
