kind: pipeline
name: build-my-site
type: docker

steps:
- name: build
  image: leins275/alg-dstruct
  when: 
    event: pull_request
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  when: 
    event: pull_request
  commands:
    - valgrind --leak-check=full ./a.out

- name: feedback
  image: jmccann/drone-github-comment:1.1
  settings:
    api_key: 
      from_secret: api-key
    message_file: a.json
  when: 
    event: pull_request
  message_file: a.json

