kind: pipeline
name: build-my-site
type: docker

steps:
- name: build
  image: gcc
  commands:
    - make
    - ./app

- name: memtest
  image: valgrind
  commands: 
    - ls -al
    - sudo valgrind ./app
