kind: pipeline
name: build-my-site
type: docker

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
- name: build
  image: leins275/alg-dstruct
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind --leak-check=full --log-file="vg_log.txt" ./a.out 

- name: feedback
  image: jmccann/drone-github-comment:1.1
  settings:
    api_key: 
      from_secret: api-key
    message_file: vg_log.txt

