kind: pipeline
name: build-my-site
type: docker

steps:
- name: build
  image: leins275/alg-dstruct
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind ./a.out

- name: run
  image: leins275/alg-dstruct
  commands:
    - ./a.out
