kind: pipeline
name: test_lab
type: docker

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
- name: deps
  image: docker:git
  environment:
    ssh_key:
      from_secret: ssh-key
  commands:
    - [ -z "$ssh_key" ] && echo "missing ssh key" && exit 3
    - mkdir /root/.ssh
    - echo -n "$ssh_key" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
    - git clone git@github.com:AlgDstructPolytech/tests.git
    - mv tests/scripts/* ./

- name: build
  image: leins275/alg-dstruct
  commands:
    - ./build.sh

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind --leak-check=full --log-file="vg_log.txt" ./a.out 

- name: feedback
  image: jmccann/drone-github-comment:1.1
  settings:
    api_key: 
      from_secret: api-key
    message_file: vg_log.txt

