kind: pipeline
name: build-my-site
type: docker

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
- name: depths
  image: docker:git
  environment:
    ssh_key:
      from_secret: ssh-key
  commands:
    - echo "$ssh_key" > ./key
    - eval `ssh-agent`
    - ssh-add ./key
    - git clone git@github.com:LanskovNV/drone-test-private.git

- name: build
  image: leins275/alg-dstruct
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind --leak-check=full --log-file="vg_log.txt" ./a.out 

- name: feedback
  image: jmccann/drone-github-comment:1.1
  settings:
    api_key: 
      from_secret: api-key
    message_file: drone-test-private/private.txt

