kind: pipeline
name: build-my-site
type: docker

steps:
- name: build
  image: leins275/alg-dstruct
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind --leak-check=full ./a.out > valgrind.txt

- name: feedback
  image: jmccann/drone-github-comment:1
  when: 
    event: pull_request
  message_file: valgrind.txt
