kind: pipeline
name: build-my-site
type: docker

steps:
- name: build
  image: leins275/alg-dstruct
  commands:
    - make

- name: memcheck
  image: leins275/alg-dstruct
  commands:
    - valgrind --leak-check=full ./a.out

- generate-comment:
  image: alpine:3.7
  commands:
    - echo "Hello World from File!" > comment.txt

- name: feedback
  image: jmccann/drone-github-comment:1
  settings:
    api_key: 
      from_secret: api-key
  when: 
    event: pull_request
  message_file: comment.txt
